project_id = "nvkjzdhpjrbaietwcnmg"

[functions.assistant-facilitator]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = true
